apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgresql
  namespace: helm-chart
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: postgresql
  version: v16.7.21
  targetNamespace: postgresql
  createNamespace: true
  valuesContent: |-
    global:
      postgresql:
        auth:
          existingSecret: postgresql-secret
          secretKeys:
            adminPasswordKey: "ADMIN_PASSWORD"
    primary:
      persistence:
        enabled: true
        storageClass: longhorn-ssd
        size: 5Gi
      #initdb:
      #  scriptsSecret: postgre-secret-init-script
