apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G # Request sufficient storage from the SSD
  storageClassName: nextcloud-ssd
