apiVersion: ENC[AES256_GCM,data:Iew=,iv:Boan/KZhJTkdqOD4/NwgAYPfNYQA+R27DRibm/3U4hI=,tag:q5hx0ZahWl+IQlf4wEKYnQ==,type:str]
kind: ENC[AES256_GCM,data:qxxf79AX,iv:6ldVHGDnUOqb+WVEMPfAP6nNAIezg/mgOjYIZT0KQw0=,tag:WOoHNsGsJpyNoMMS57Bjrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:y/NqcPrWKL+tIXHLig==,iv:7CVM3+g3pw7a29YknmqSRuEwvuRCfzGrVdicc9DvXHo=,tag:GYU3WSBPA9WCeXLZ4uGz/w==,type:str]
    namespace: ENC[AES256_GCM,data:6zXrCHCGdGz68w==,iv:WdDsDzXXf9VbuS+MH5vaxqR8s60/IyaEtKLycLjx9WQ=,tag:Nyq+6pqQYrgEuEht73YFsg==,type:str]
type: ENC[AES256_GCM,data:WwfZznr1,iv:ehDwZBTFja/wIFJ/9iTDpRjm35d4cktE0YvYbJ9oBck=,tag:s8Pq/RADjQHRdOrDcTndhg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:GBto8ZnhEHiilDlh8UKoZaz3Cn2+ka7p07ulGpmo6QI+Yvg=,iv:EOqAxVD14jH15tKk2nqC54EqHGUfazNapv5x/m2tiOQ=,tag:iiWv5bJmL0qSiKXE02Ze7Q==,type:str]
    postgresql: ENC[AES256_GCM,data:SM/CjHhOz4GOXvPpVjxtmQkyGarr350F4XrAX6p312ZprXtGga+cfIkyVE5/cvVquFwAa/uyDcuopvIyQIpJA/d2qJph/tFHKb8zFpSPocoLlytO8IoPYRNKvK0yktAb3DKE3PwlKadYXcrN1ZBV3gjFsq/g6OkulXbs6rWrfZ4WAPcdKQBEblUHySE8PIeMrXZkS8l7jd7x/j8Q6Co0iRpkKfEdfhNGzbOgitylS94EWfgkqHaYJ3bvEcxujYBGK1n6Q00bWKV8190wQvTE7LsegCgYkqrkA7cgU2B9ux2Jit9YBaSnJZrjVnmSMvPxfAjLkLDp3LJe2XHX7giDD/mbEIpLP5xc9eXmTmE4Zfrv+pvN46ZrpizmHiC7SZ5CqifNVk1qFWvgwRql+dPwM8Fk/c3rkqujvgXpBbQzSw7f2nDm95QarIBdpRSM3aVzkWxi,iv:aRd4uaoT9s1x+YW/q5JiMfYelUfg77tlTyaPJieIBgc=,tag:TH/bhRTM8vX12KBbneLrog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13d0vgu5aykqa425gsaewmgadzdud240sqhlnalz6hr4z2pnfw3kqgxdm9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOEt2U1lRVUhwRDgrQ01p
            Ri9IMWwwdk1MTTQxdE43M3hlVzZncjRYaWxjClpTV09oZU1XNitKRHhwNURYUGhK
            OFRyR1l2YlBTREpiSW1USWNNNC9zOWMKLS0tIGN1cXRDRzA4c3A5ZjBzYlRacUNX
            WjhlUkI3ZW52akNnY1VMQ0Q5djVIeDgKfMZEGffhEoVfJnCRB8SGHXQuQHqqHqnR
            8x00djjO/JFNoXFTAalxTmjcSvtKWTnFBpUEVZqze13OYG6HgZkNuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMm9zNjJWMWUzUmRaOHJi
            RktEWW9RQWFhcW44L0RGdm1IenpjUXpoNms0CkVCVzJiVzBoc1dzVjhONGpaQUda
            OUJ2VTJXc29laE9JMFZub0RtTnd5a2cKLS0tIDVTTTVCNmlualVNSm4zQVh2Y0VS
            NHIxYUlvR2RUSk04VzBSL2wvdjRhMk0K8vStDwJT6MtDKoJieNwNvAHd6WSL9XUw
            SMKIMAqbElgUkL29NOaIK9vTSEUGdK2X462aCYR+4XgRCFoogDO0+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T17:45:39Z"
    mac: ENC[AES256_GCM,data:v8pPHBdocXH5FZa+EiXJC4Wb/yFg6nknIPUrrtV/+RIkh6kod7HNSbWMVFt8KnOrpWRe/L+C/wepfbCSCruNxFMJEE8ZQJTwRW2vxMmBbFRw50qwrUhUBYUgzfGITPXMhncJYv0kiZZW6stBC1yCc3t2nx342i9MJLx5jNuv/jY=,iv:uTbfRzP73NneE4pYarvDwA0WUR0sVN2OZhDceqYUgiA=,tag:oW/cFG6MJZhkg5Jhp+fQpg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
