apiVersion: ENC[AES256_GCM,data:+Ow=,iv:ZC1BB8b/xooLV5nv+VGb2tN6TJcq4jsZxADxUOzTpJo=,tag:2mrpMbPK1GdzLJiq+NY0LA==,type:str]
kind: ENC[AES256_GCM,data:HflUOkxs,iv:/qyvbUKziEB0znSBE4KNpUXTxoJjlA8f7NLYDT9I2H8=,tag:EesAYG2VwvC+HExj0zgPQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hPlgbjGSzcKWzZnHVEHa,iv:w7zhVJk7/Gl9LxcNMteDLTQna4qkGmEKr20TRH43gak=,tag:ZvWNpBaqiIx+SaNFAE+4VA==,type:str]
    namespace: ENC[AES256_GCM,data:YhQAmdCi,iv:Y4I+hn9dGEesfhL9/UznEbLqHKsEs9MlFZHfEWxQ/Ms=,tag:jv7UF2CEMKlr2RyynTjIBQ==,type:str]
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:/P8cnA==,iv:xFBgTb75McfDQ1gRUB9O92BPWIYF5fnnOBCA4Ye2Lr0=,tag:uC9Rc0Qodp3J6FZnC+jlCg==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:QOYgqA==,iv:lkXBkvlsan6tY1Jd1FpkypHVrmdvpJEAljVjXE843So=,tag:POgxeyAV+8AtFtEqNzJl4Q==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:OODsV+1v,iv:5+ihh9ILSy5ykbXowLzho1O6kkzL9RPdsvo0JgfeUbM=,tag:NtHcXmzriJgNnRxys6r4og==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:bGnBA+V5qQgNM9lwRZv6WFvwhs64E4g8FkW51yCLUWTiQ95SQgD/MbaUqkXhZk6YNWhdGjrjOeddJ79aB4jK8dVo6yQi/gpahLoy06ndML5kYHUH4B1D338hilUmfqcZZGOMwNzHFtBTmQ5M9qpo0CBinRRMh/Zr,iv:39HFLjpYzlh0aCTmhSTgyAdNTHdG7zGVj8x0Sqm+XfA=,tag:qdkCxA0yGZHN8EddOUfRCw==,type:str]
type: ENC[AES256_GCM,data:aXB1Kegt3VrEjAHk+o1tIp+lU3DivXinhoFdBRQo,iv:5tGVm7aOA9tTrDbvIApLDChdgoDZ1ugedXhlvj5Tceo=,tag:sdkpZnCqyYV5tghm0KUb8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13d0vgu5aykqa425gsaewmgadzdud240sqhlnalz6hr4z2pnfw3kqgxdm9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUi9mcG5wK2Q1ZmI3ei9K
            SmJwN2VIR1ZIcndwVllpTDJ1N3lLWktua1dBCnlvVUY4SmpxYldpOEwrcnJUY3hJ
            enB6VnlxRGZBcHRoUGx0a0hBbHFJN2sKLS0tIDJJaWdPRlFveEhlT3RvSnBMZjJU
            cjBrOUtqUFFmbFExRFFOUllQVk9XQ0kK/XFicKSB4QzfAMrUtDWyPxbMBcjI8wlm
            EBnS58EapoGCpdi1XdSnR+Ssb1rqrfO1MjszKOzTZKUITn42pLSS0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMVl0VGwzWngvR2hsTnJ2
            SWFUZHVrRGl3TXV4NXJReG9PZHh3RUpIUkVVClkvTDUrNTRkVXdQbGJOTXVUczYr
            ZmR5NStwNTZLeHJYcGlLODRENnNZdU0KLS0tIGJNbjBQZ0IvY3dYY1o1eEdVaVAx
            VXBHOTNkU2ZsSitoeW1tTnJTU2NzSHMKQVFjE3B6Pyht2UKF053+nFGCvl6tStui
            cFen5ShFLn+5rXOdt74XI+NZdzFsfqHqpoOFjXHNCirft4s7wC6FZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T18:41:02Z"
    mac: ENC[AES256_GCM,data:FxZv+YaFiGyMW3muwow7gZ8QlEMQ2QMEdpZ1SoZywdgX8ywViVeqepRk2iRXL2NjolG1W03CAp/OSa9baGup70PvGkLay7uySf5uLgMGDd/+LEn1Y3jfgb76pEKTQp8wR8hBIrzu4u0c9/f3DOM4v3XJ2SasYxqBCPPiMddDnI8=,iv:blmKrjynmHhwO02hh2KK0Vbh4rgQ4lNBC9kMiz/sYH4=,tag:k1umik/79kBYijml6zhxOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
