apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harbor
  namespace: helm-chart
spec:
  repo: https://helm.goharbor.io
  chart: harbor
  targetNamespace: harbor
  createNamespace: true
  valuesSecrets:
    - name: harbor-secret
      keys:
      - password
      - postgresql
      #- redis
  valuesContent: |-
    externalURL: "https://harbor.vivenot.dev"
    expose:
      type: ingress
      ingress:
        className: nginx
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          core: "harbor.vivenot.dev"
    redis:
      enabled: true
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: longhorn-hdd
        chartmuseum:
          storageClass: longhorn-hdd
        jobservice:
          storageClass: longhorn-hdd
