apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
  - wrangler.cattle.io/on-helm-chart-remove
  generation: 1
  name: longhorn
  namespace: helm-chart
spec:
  version: v1.9.1
  chart: longhorn
  repo: https://charts.longhorn.io
  failurePolicy: abort
  targetNamespace: longhorn-system
  createNamespace: true
  set:
    defaultSettings.defaultReplicaCount: 1
    defaultSettings.defaultDataPath: /mnt/sdb1/longhorn
    persistence.defaultClassReplicaCount: 1
