apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ssd
  namespace: longhorn
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  diskSelector: "ssd"
  # nodeSelector: "node-tag:ssd" # Use this if you're tagging nodes instead of disks directly
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
