certFile: /etc/blocky/cert.pem
keyFile: /etc/blocky/key.pem
port:
  dns: 53
  tls: 853
upstream:
  default:
    - https://one.one.one.one/dns-query
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus.txt
    adult:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/nsfw.txt
  clientGroupBlock:
    default:
      - ads
    kids:
      - ads
      - adult
caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true