# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6bc555b5-1a2a-445f-81ff-10d2328f2b42";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A5AB-5FFD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/sdb1" =
    { device = "/dev/disk/by-uuid/e8c9abad-f77c-477d-bd54-ab1290da6714";
      fsType = "ext4";
    };

  fileSystems."/mnt/sda1" =
    { device = "/dev/disk/by-uuid/9d5202fd-af50-4477-af43-c46066eb3433";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/894f8860-7094-432c-ac0d-cc31d10a3730"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-2b71d6521013.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-5e4ab935887e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-91b7610677e7.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-f57d0af5e85f.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth204b85b.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth26d89ef.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth385acdb.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6401e0d.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9b6b77f.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9c3d699.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethdd815cf.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf4e5699.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
