apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitlab
  namespace: helm-chart
spec:
  repo: https://charts.gitlab.io/
  chart: gitlab
  version: 9.2.1
  targetNamespace: gitlab
  createNamespace: true
  valuesContent: |-
    global:
      edition: ce
      intialRootPassword:
        secret: gitlab-secret
        key: ROOT_PASSWORD
      hosts:
        domain: vivenot.dev
        externalIP: 192.168.1.201
      ingress:
        provider: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: 10g
          nginx.ingress.kubernetes.io/proxy-buffer-size: 250m
          nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 500m
        tls:
          enabled: true
          secretName: gitlab-tls
      psql:
        host: postgresql-postgresql.postgre.svc.cluster.local
        database: gitlab
        username: gitlab
        password:
          useSecret: true
          secret: gitlab-secret
          key: POSTGRES_PASSWORD
      minio:
        
      
    
      
    
      
