# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6bc555b5-1a2a-445f-81ff-10d2328f2b42";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A5AB-5FFD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/sdb1" =
    { device = "/dev/disk/by-uuid/e8c9abad-f77c-477d-bd54-ab1290da6714";
      fsType = "ext4";
    };

  fileSystems."/mnt/sda1" =
    { device = "/dev/disk/by-uuid/9d5202fd-af50-4477-af43-c46066eb3433";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/894f8860-7094-432c-ac0d-cc31d10a3730"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.cni0.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.flannel.1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth057bf117.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth0788c134.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth080a95be.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth0fdabb0b.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth16322ea3.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth17f8a76e.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1e5a63f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth21321a3e.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth225d687b.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth22f75d8f.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth24cfee79.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth28136dd9.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth29c8b94f.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2aff291e.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2cfecc84.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2f2c64b1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth30944025.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth320f7bde.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3493b3bd.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth35a45687.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth35b02f35.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3b68ea99.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3f784d61.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth41dbab79.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth47d6413b.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4eb5bd10.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4f858f12.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5503ae48.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth57767587.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5b41c866.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5c3b08d4.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth607b472b.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth671fb3ee.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6a5b8f68.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6e78989c.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth76d22310.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth807c1479.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8616c5b2.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8c6c3321.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8eedc3cc.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth902e4d29.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth905be196.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth90da7d43.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9167319a.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth945d3e3d.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth98bf8be1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth99016276.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9bc78e97.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha2597722.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha25c7a70.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha52ce113.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha7afe26d.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha864f9b6.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethaacad6ff.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethaca132ab.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethadd5de87.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethaeb13af5.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb1c05534.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb28db0e9.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb58b0e07.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb8ce341e.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethbff0dd81.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc32efe9a.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc463b4bb.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethc850d3e1.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethdda05d3e.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe2586cb7.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe28cfdab.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe31d4922.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe34ad57b.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethec587600.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethed10c8e4.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf15586f2.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf27c0bee.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf48611b6.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf9a21c3d.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf9d1fa0d.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethfa68350d.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethfaf490e2.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethfd9ea334.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethfee12842.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
