apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: helm-chart
spec:
  repo: https://nextcloud.github.io/helm/
  chart: nextcloud
  version: 7.0.0
  targetNamespace: nextcloud
  createNamespace: true
  valuesContent: |-
    nextcloud:
      host: nextcloud.vivenot.dev
      existingSecret:
        secretName: nextcloud-secret
        usernameKey: NEXTCLOUD_ADMIN_USERNAME
        passwordKey: NEXTCLOUD_ADMIN_PASSWORD
    persistence:
      enabled: true
      storageClass: longhorn-ssd
      size: 10Gi
      nextcloudData:
        enabled: true
        storageClass: longhorn-hdd
        size: 1Ti
    internalDatabase.enabled: false
    
    # This does not work for some reasons, will default to sqlite
    externalDatabase:
      type: postgresql
      enabled: true
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: NEXTCLOUD_DATABASE_USERNAME
        passwordKey: NEXTCLOUD_DATABASE_PASSWORD
        hostKey: NEXTCLOUD_DATABASE_HOST
        databaseKey: NEXTCLOUD_DATABASE_NAME

