apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: helm-chart
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.18.2
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    installCRDs: true
