apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging # <--- Change to "letsencrypt-prod" for production
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # server: https://acme-v02.api.letsencrypt.org/directory # <--- Uncomment this line for production use
    email: axel.vivenot@gmail.com
    privateKeySecretRef:
      # Secret for storing the ACME account's private key
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
