apiVersion: ENC[AES256_GCM,data:AFg=,iv:PM0d7FIJfLzzKGn0tA4/pINEOrHxdF2D3bzBfZ7Ce+M=,tag:8rTNhMhaWGTEF5X+3l6SaQ==,type:str]
kind: ENC[AES256_GCM,data:5m/QYeo9,iv:macHnaWEr0lf/ia5UL0hCi8fz8PO6JEXwimuc3H7RJc=,tag:3gssSsjQWhlGfUPcrz0pAg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9QG/0Ne2kWoUR4X9sWE=,iv:e1tFUg/YRPPLiK1/foHk4Uud89tqhueDnvoKs3aVGSc=,tag:Fhv6kkN7y6LNaqLDgYlSoA==,type:str]
    namespace: ENC[AES256_GCM,data:8oTSsy6fhA==,iv:vavn4v38SdvbTGnjBsAWL2I0/wNZIDKthpPa9yZPjVg=,tag:oZJ25SUHiV9Qd4Iv49EV6Q==,type:str]
type: ENC[AES256_GCM,data:lDnUvsIO,iv:lwNJHEb0dn15F2aqWsCmMvwYWbsHfStfJoahoZ8G1wo=,tag:MeBPrbJLQ3KBKihf1LcTtA==,type:str]
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ty4AKrnpRlssSo3EM1nvBTdQ5VlHPwl10sAKhKlFe0lhQdq9dnYoP4pe8iI=,iv:S11Nua5uZc2l33trFlJJhcIisq2hU04mJoMe085lf9M=,tag:6olAYx02dkz31IBZ+3qY4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13d0vgu5aykqa425gsaewmgadzdud240sqhlnalz6hr4z2pnfw3kqgxdm9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTEx3MkpaRGluTGgyQkJW
            Rkx2alZpRXBnZ25EMTNoZFdHSGtWT2luRUZ3CnEzTFR3RUpVcStISm5Sc3JhdWk3
            clZEakR0U0VyM2xYeVJxZTFiQ0k3Z2cKLS0tIEpXSVdtWCtnRzZTQVJiVFdqTHNs
            TC83bEg2WHFXdUwxT2RSVFFSMjhDZG8KUawKf5GBBLlIazj+nHYzuGIo7Lgki0dx
            uZdGvIc7+/Kf//sbUGQRd6Y0oVQCiv4m2kxDbVPwAilgVAWH8XMN8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZUR0cU1SbUUyaVg4T3BC
            SEE4OVVZUlZLRTZISWZZbjQwRmxScURlcEdnCm9ISFo1QUI3T2wvQUZaYlRJNGRa
            OURzQ1F3RHo5ektnUVZmZDFrS3lFQXMKLS0tIDBZOXhZWWRFMDBUTnFwVFlCNzZh
            VmllSmgxZURSaFdGWlpkVGVlNG9vU0kKDnhsZjRWaKDPbxbwf4ibBa/9e5M2zUSV
            vTpVjUBNkosvlSfA5Z3/iX3qa7sWHT8Nv9wqbNCa3mC+5ztkpare/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T14:52:44Z"
    mac: ENC[AES256_GCM,data:EDV6d3Z76gBxNvJed/cn9tHX2ZcDGdEz42r67gqF5sLCXG6QdMg6DhAnIvInzoQiEf3YKCQ7KoSg34i/vH3r4KZaIGD9ZkeeVrqE03xtGbBUW5BpPHIRQ/PHgzbqqhNpoxO6Zm5cSXrRxfo3UQXC64xgOAOuU16bjfT6IEYIx0w=,iv:VpaSUL3l6PRw0GqzgwyAZ0xGb8Jh24u6W+p1Ji721do=,tag:1fc+jo05FZbIcgKDtO6veg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
