apiVersion: ENC[AES256_GCM,data:P3A=,iv:YCDKn7P60cJm3qutmgiIaXcNrhDh/gVrmkJkHafTtr0=,tag:MwEhMsk6OKP2/4aYj/Kdmg==,type:str]
kind: ENC[AES256_GCM,data:bC4EPZYt,iv:gRFwEeMMAOOZ2PAXdfn1fpFPamkXOUv7Vd2SgWZYehc=,tag:ly9BRvPjCD9WY6SjHYgdLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fK6gjLHuL/mrG7X6YTvWGFVi2oqMPyT4wXc=,iv:vbW2+Zd23aiA1wpH4qZ5rX/mJiI3G6h0bgRpYbaKwEI=,tag:GFJPSRT0Xh7ATwAPTc5Acw==,type:str]
    namespace: ENC[AES256_GCM,data:VJXh2K/jtw==,iv:wwDcdXA8Ikr29gZUZRYG1cx8cyDu6zmMbUk9RUB7OiE=,tag:yD4PxUKs5B+KZEjoD8wDpg==,type:str]
type: ENC[AES256_GCM,data:+ORHQCpO,iv:ONELwHqQ3AbhZLmKkH0Si8v4LbeqGITE+EduX/QHzLU=,tag:2USOvA9yHa28q8PTntz5NQ==,type:str]
stringData:
    create_user.sql: ENC[AES256_GCM,data:P9SPnsW7ivsefFTfPmkaWvHNMI+MM67M3DPCTBTM0vYxyYjy9PEvzulyTABoo16TkK2MGtCUhOEbBA0DeC5T8FvPtyxgEmtZXhzLHA0tgvL1QET7PnbI7YIGNSZDchUnJ9C+x207Kg4SOXzAMLVa65h8PmIBWTQbjAp7ghR2YJIQrjr0y4fIzpJNNAsIBpu3ZBRYVoEPlApj/qHMGGFoETZqJk72rZJApB9xJ8gQkqxJQ91YdXX4BOiIAVJRaUyP8rrS3LWQiqjQrWGIAjjxObpiekCnXtOYYL6IfA8bHxrl6P2BrThY8iUbjvo9YYdN0POZlJVQ5kH6XxrkYrE=,iv:uvsdSJ5xQ7jIbW3pTwAxgI06m80mSkKfbLwSLnKBvdU=,tag:Oaju5iJapRfsN5Jsj95kqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13d0vgu5aykqa425gsaewmgadzdud240sqhlnalz6hr4z2pnfw3kqgxdm9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ2dOd2NYTTFFaFgxOG1E
            QjQwcjRkazlaUStxZDZuek9vVmUxVVRkRFR3ClRWNlNSdFNyQ01mRFRGcGYyRGNX
            ZDRZaXl0WExaL1F2MWx5dS9sZURodzgKLS0tIFdXcDVzRTFBTitPOXZkQ1RMTENN
            T3hocmNIVGIwb09vMHFieHVGdXplbncK6lKZnZiFzR8w0oUV9FfDSlwfsS3Q2CsL
            NMDfF3eRxs/4woRkgeNDQBTqz5qIpBiCa0xwhBTaFO+TWJWvzoCtkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d2584z5sc0jkl97zfztuvfguxhmdzrqj323clzne4e533eegpfeqf0dam5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UGFUOXB1M3V4N0VTMWFl
            RC9SYjg1cndBTzFzZ0MrTklHdk0xR2lGVXc4CmVSMnBneGVPL1phN29zR3Z6UDFJ
            U0MwOGttVzZxZXJFRExxcGgzZmJWZ00KLS0tIDFmT1ZnV2dhbFBKTnhWdjA2RExt
            eFdyNmZ1dHduZG1RSENNczEzbHpSOWMKEYesbIYp+S6vwJyquk3yBpAHo4Kt3bR7
            AZz6td0iuWiP6NwsZ4NpLiywMZIqUyobLTzmkXHQ9HiXMnsnxGsN6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T17:57:10Z"
    mac: ENC[AES256_GCM,data:4w+BIK7rkrw3oPNRDsF7xQDpPU57cgQqsedChsWAlJHK3W+g25cVNeyvnGONoUVrirLTmrJuqdZEsFNuRGNifmYiDMSyY37qeSluYvoj59t9mIxS17RW2tic7Yus0aTe0a6k/LyxOZsQwJBKu7aIrROj5E+EP05+qHpF+6R9wr8=,iv:qIjOR0mILQjYYpSLHnSsTI2N+tgQxXsdERW3uBjkRCk=,tag:W2brebbgoKib7mB/5xfvAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
