version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 1000:80
    volumes:
     - ./vw-data:/data:rw
    environment:
     - SIGNUPS_ALLOWED=false
