apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: helm-chart
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  version: v2025.6.4
  targetNamespace: authentik
  createNamespace: true
  valuesContent: |-
    global:
      env:
      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__HOST

      - name: AUTHENTIK_POSTGRESQL__NAME
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__NAME

      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__USER

      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__PASSWORD

      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_SECRET_KEY
    redis:
      enabled: true
    server:
      ingress:
        enabled: false
