apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: helm-chart
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  version: v2025.6.4
  targetNamespace: authentik
  createNamespace: true
  valuesContent: |-
    global:
      env:
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__PASSWORD
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_SECRET_KEY
    authentik:
      postgresql:
        host: postgre-postgresql.postgre.svc.cluster.local
        user: authentik
    redis:
      enabled: true
    server:
      ingress:
        enabled: false
