apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: helm-chart
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  version: v2025.6.4
  targetNamespace: authentik
  createNamespace: true
  valuesContent: |-
    global:
      env:
      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__HOST

      - name: AUTHENTIK_POSTGRESQL__NAME
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__NAME

      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__USER

      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_POSTGRESQL__PASSWORD

      - name: AUTHENTIK_REDIS__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_REDIS__HOST

      - name: AUTHENTIK_REDIS__PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-secret
            key: REDIS_PASSWORD

      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secret
            key: AUTHENTIK_SECRET_KEY
    server:
      ingress:
        enabled: false

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-ingress
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - authentik.vivenot.dev
    secretName: authentik-tls
  rules:
  - host: authentik.vivenot.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authentik-server
            port:
              number: 80
